### ISSUE TITLE
Final Review

### ISSUE THREAD

**Issue by robi-y** [turner11/ASOSMA#11]
Overall very nice work. Is still needs last edit to make it a complete and coherent chapter.
Here are some more detailed comments.

- [x]  I believe some of the stages issues were closed without being taken care of..

- [x] do we need the [homework progress] folder? if not, please remove
- [x]  You need to remove reference to stages (e.g., (more in stage 2)), so the chapter is more coherent,
Also some of the titles are taken from the instructions and include redundant text
- [x]  Main page: abstract should come before the introduction
- [x]  abstract: make last edit, and mention what you think is the main contribution of **your work**. Most text in the abstract should be removed or moved to the introduction
- [x]  Model of development: I suggest adding that this is an open source development model
- [x]  Views and Perspectives: missing introduction to this section. Images are not linked properly (at least I don't see when reading on github)
- [x]  Metrics: nice section! still missing introduction. I don't see a discussion regarding the tool you tried.
- [x]  Summary: the last link to the course book, should be moved to the introduction as part of
- [x] Report on communication with team?

Sorry for the delay in review, I was too busy with the BSc final projects. Let's try to submit finally this week and the I'll submit grades.
Please comment below your reply to the issues above.

@turner11 @PhillipKatz @Elisj52

**Comment by turner11** [comment]
@robi-y , "_Model of development:_" where are you referring to?
@PhillipKatz , @Elisj52  , "_Views and Perspectives..._" Living to you to decide if and what you want to update in your section.
@robi-y , "_Metrics_" - did not try any tool - did not get to it due to the long installation process...

**Comment by PhillipKatz** [comment]
The broken image links are probably the result of renaming "HToolBox" to "allReady". I'll fix it in a moment.
Which stage issues were closed without being taken care of? What do we need to add?

**Comment by robi-y** [comment]
@turner11 Model of development, in the inrto
@PhillipKatz stages 2-3

**Comment by robi-y** [comment]
Any update?

**Comment by turner11** [comment]
I sent a new pull request...


Was I supposed to do anything else?




Sent from my phone







From: Reuven Y.


Sent: Friday, July 14, 17:39


Subject: Re: [turner11/ASOSMA] Final Review (#11)


To: turner11/ASOSMA


Cc: turner11, Mention






Any update?

**Comment by robi-y** [comment]
OK, overall very nice work, hope you learned and enjoyed
I had to manually delete the leftover [homework progress folder]
See your result here: http://jce-il.github.io/ASOSMA/allReady/
Regards

**Comment by turner11** [comment]
I deleted the folder as well...
I guess it did not show on github because if the way [git indexes works](https://stackoverflow.com/questions/10074582/git-how-to-remove-empty-folder-and-push-that-change#10075480)....

**Comment by robi-y** [comment]
No, it was in the top directory and even contained 2 files
https://github.com/turner11/ASOSMA/tree/c90518b074c205737139c1061578729dbbf6169a/%5Bhomework%20progress%5D
