### ISSUE TITLE
Stage 4 Presentation Review

### ISSUE THREAD

**Issue by robi-y** [turner11/ASOSMA#8]
- [x]  rename to allReady
- [ ]  your contribution to project (documentation)? input from team?
- [ ]  Missing architecture description/modeling
- [x]  Nice perspective tables

Slides and presentions:
- [x]  too much text in my opinion

**Comment by turner11** [comment]
* rename to allReady - Done
* We did not have a real contribution to the project. We did not get to it with the limited time we had for the assignment...
