### ISSUE TITLE
Stage2 Review

### ISSUE THREAD

**Issue by robi-y** [turner11/ASOSMA#9]
- [ ]  Code analysis tool: output not so clear
- [ ]   What is the value of the Structure101 diagrams?
- [ ]   Can we find more info on internal architecture 
- [ ]   Add the metrics from Structure101
- [ ]  Missing architecture description/modeling

**Comment by turner11** [comment]
Phillip, Eli - assigning to you since it was in your chapter...

**Comment by turner11** [comment]
@PhillipKatz , @Elisj52 , I think this is the issue @robi-y  referenced as "_closed without being taken care of_" in [issue 11](https://github.com/turner11/ASOSMA/issues/11)

**Comment by PhillipKatz** [comment]
Added conclusions to the graphs in "Views and Perspectives", reasoning and proposed solution to indicated problems. We can't say much more about it since we weren't able to compile and run it - insights given by someone who didn't have a close look at the system can't be rigid.

**Comment by robi-y** [comment]
Fine
